spring.application.name=eventbooking
# ===================================
# SERVER CONFIG
# ===================================
server.port=8080

# ===================================
# DATABASE CONFIG
# ===================================
spring.datasource.url=jdbc:mysql://localhost:3306/bdduser?useSSL=false&serverTimezone=America/El_Salvador&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===================================
# JWT CONFIG
# ===================================
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# ===================================
# OAUTH2 - GITHUB (Punto Extra)
# ===================================
spring.security.oauth2.client.registration.github.client-id=Ov23liQK2DHuwb1ArBzm
spring.security.oauth2.client.registration.github.client-secret=4839ad36810d0042701fee30ba73b10b8add395c
spring.security.oauth2.client.registration.github.scope=user:email,read:user
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# ===================================
# SWAGGER / SPRINGDOC CONFIG (Guia 9)
# ===================================
# ===================================
# SWAGGER / SPRINGDOC CONFIG
# ===================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true

# ===================================
# LOGGING
# ===================================
logging.level.com.udb.eventbooking=DEBUG
logging.level.org.springframework.security=DEBUG